sudo: required
language: perl
services:
        - docker
env:
  matrix:
    - OS=debian DIST=jessie PACKAGE=deb
    - OS=debian DIST=stretch PACKAGE=deb
    - OS=ubuntu DIST=trusty PACKAGE=deb
    - OS=ubuntu DIST=artful PACKAGE=deb
    - OS=ubuntu DIST=xenial PACKAGE=deb
    - OS=fedora DIST=27 PACKAGE=rpm DOCKER_IMAGE=fedora-rawhide
    - OS=fedora DIST=26 PACKAGE=rpm
    - OS=linuxmint DIST=sonya PACKAGE=deb DOCKER_IMAGE=debian-stretch
install:
        - sudo apt-get update
        - sudo apt-get install git devscripts debhelper quilt
script: ./build.sh
deploy:
  - provider: packagecloud
    skip_cleanup: true
    repository: snapshots
    username: ${PACKAGECLOUD_USER}
    token:
      secure: ZkwM5okisd28XRj8QSiKLMVKf0kKJVnRiWYAlmtwLo46KueWl4C/sEm4LvZA2qJ7E5FMU7eUEkCmsIPsfYWgyKivSBtLlMT64wwt44d33FXcQ6oMeLFb4MiaH9nbnRseaxI3Zq6ux+Rg5zAq3H9WmWQbKPadoYQM328KLlEQCGnzysCb52Uwh+k0VlZG93k7lzyo5Y9Jl/Arsb2Y0VimRcC9ZIUFzQl08xQoaz5Nb3AY6uSn/J1d7iuTDAL3pkenlF63YnjoN0xf1ywZ61HYnfVxBVP4l5UiqYoLw2nIODBjSITTIttFVh2rQdgffFsdDCsSesoqGnf68HpY5LRVeYfhb29AEId0v6SGUdeD8axKQbXpHxkgMWFMzdtIkrmg8njKjplZgIPV2bE6dg6HHrXdlUZuG/HHCeQlCr75/luBo4dhXOLEzOJmeR6cezmxd4UEI8IxrNqT+jjPLn0jr8TaK/tDA+wGD3aSScAaInBkWdgXBz+koXLEpAi7JBkw88d4Bcrxu1aBQ55834afaDgU1UH8sSg/HGlXdKZBzr3B9wt4NId//fcGqzKfAm3xQMSou0o6yxbj2Qy9TujE2Z0ejStSyMYRZYUoqPSXKVvK1K9bytkV3gftWekZRZ2y9Zjec7c6sUt2a20xAWsT1gHYyaHemayFtuqIpl2bLI4=
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      branch: master
  - provider: packagecloud
    skip_cleanup: true
    repository: asbru-cm
    username: ${PACKAGECLOUD_USER}
    token:
      secure: ZkwM5okisd28XRj8QSiKLMVKf0kKJVnRiWYAlmtwLo46KueWl4C/sEm4LvZA2qJ7E5FMU7eUEkCmsIPsfYWgyKivSBtLlMT64wwt44d33FXcQ6oMeLFb4MiaH9nbnRseaxI3Zq6ux+Rg5zAq3H9WmWQbKPadoYQM328KLlEQCGnzysCb52Uwh+k0VlZG93k7lzyo5Y9Jl/Arsb2Y0VimRcC9ZIUFzQl08xQoaz5Nb3AY6uSn/J1d7iuTDAL3pkenlF63YnjoN0xf1ywZ61HYnfVxBVP4l5UiqYoLw2nIODBjSITTIttFVh2rQdgffFsdDCsSesoqGnf68HpY5LRVeYfhb29AEId0v6SGUdeD8axKQbXpHxkgMWFMzdtIkrmg8njKjplZgIPV2bE6dg6HHrXdlUZuG/HHCeQlCr75/luBo4dhXOLEzOJmeR6cezmxd4UEI8IxrNqT+jjPLn0jr8TaK/tDA+wGD3aSScAaInBkWdgXBz+koXLEpAi7JBkw88d4Bcrxu1aBQ55834afaDgU1UH8sSg/HGlXdKZBzr3B9wt4NId//fcGqzKfAm3xQMSou0o6yxbj2Qy9TujE2Z0ejStSyMYRZYUoqPSXKVvK1K9bytkV3gftWekZRZ2y9Zjec7c6sUt2a20xAWsT1gHYyaHemayFtuqIpl2bLI4=
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      tags: true

after_deploy:
        # Prune old packages from packagecloud. The last 5 should be enough.
        - pip install -r ./packpack/tools/requirements.txt
        - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots deb ${OS} ${DIST} --keep 5
        - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots rpm ${OS} ${DIST} --keep 5
