site_name: Ásbrú Connection Manager - Docs
docs_dir: doc
site_dir: out
site_url: http://docs.librenms.org
site_author: Ásbrú Connection Manager
site_description: Ásbrú Connection Manager user and developer documentation
repo_url: https://github.com/asbru-cm/asbru-cm
edit_uri: edit/master/doc
repo_name: GitHub
theme:
    name: readthedocs
nav:
  - 1. General:
      - Changelog: General/Changelog.md
